# Generated by Django 4.2.16 on 2024-11-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='equipments',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='reservation_system.equipment'),
        ),
    ]
